spring.datasource.url=jdbc:h2:mem:healthhub_jpa
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

# Show SQL + format it nicely for learning purposes
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Show bind parameters (so we can see N+1 clearly)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
server.port=8080
